import { Inter } from "next/font/google";
import "./globals.css";
import Components from '../Components/Navbar'
import Navbar from "../Components/Navbar";
import Footer from "@/Components/footer";
import AuthProvider from "./AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar/>
          {children}
          <Footer/>
        </AuthProvider>
        </body>
    </html>
  );
}
